<a href="https://colab.research.google.com/github/vishweshwarank-2006/Hands-on-AI-ML-Workshop-Implementations/blob/main/ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Classification problem using DL
import tensorflow
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import*


In [ ]:
data = pd.read_csv('/content/breast_cancer _ day1.csv')

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [ ]:
data.head()

id diagnosis  ...  symmetry_worst  fractal_dimension_worst
0    842302         M  ...          0.4601                  0.11890
1    842517         M  ...          0.2750                  0.08902
2  84300903         M  ...          0.3613                  0.08758
3  84348301         M  ...          0.6638                  0.17300
4  84358402         M  ...          0.2364                  0.07678

[5 rows x 32 columns]

In [ ]:
data = data.drop(['id'], axis= 1)

In [ ]:
data.shape

(569, 31)

In [ ]:
#earlier we had 32,now we removed id, and it became 31
# x = must have 31 features, y = cancer or not, y must have diagnosis column
x = data.drop(['diagnosis'], axis =1)

In [ ]:
x.shape

(569, 30)

In [ ]:
# x has 569 entries, every entry has 30 features
y = data['diagnosis'] #1-D, shd have not two brackets '[[]]'

In [ ]:
y.shape

(569,)

In [ ]:
#we use standard scaler function because we have different data types thats why
#and also we are converting the label encounter to integer
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y=pd.DataFrame(y)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)


In [ ]:
x

array([[ 1.09706398, -2.07333501,  1.26993369, ...,  2.29607613,
         2.75062224,  1.93701461],
       [ 1.82982061, -0.35363241,  1.68595471, ...,  1.0870843 ,
        -0.24388967,  0.28118999],
       [ 1.57988811,  0.45618695,  1.56650313, ...,  1.95500035,
         1.152255  ,  0.20139121],
       ...,
       [ 0.70228425,  2.0455738 ,  0.67267578, ...,  0.41406869,
        -1.10454895, -0.31840916],
       [ 1.83834103,  2.33645719,  1.98252415, ...,  2.28998549,
         1.91908301,  2.21963528],
       [-1.80840125,  1.22179204, -1.81438851, ..., -1.74506282,
        -0.04813821, -0.75120669]])

In [ ]:
x = pd.DataFrame(x)

In [ ]:
# x has been converted to dataframe
x.head()

0         1         2   ...        27        28        29
0  1.097064 -2.073335  1.269934  ...  2.296076  2.750622  1.937015
1  1.829821 -0.353632  1.685955  ...  1.087084 -0.243890  0.281190
2  1.579888  0.456187  1.566503  ...  1.955000  1.152255  0.201391
3 -0.768909  0.253732 -0.592687  ...  2.175786  6.046041  4.935010
4  1.750297 -1.151816  1.776573  ...  0.729259 -0.868353 -0.397100

[5 rows x 30 columns]

In [ ]:
from sklearn.model_selection import (train_test_split)
xtrain, xtest, ytrain, ytest = train_test_split(x, y, train_size= 0.8, random_state= 0)

In [ ]:
print(xtrain.shape)
print(xtest.shape)
print(ytrain.shape)
print(ytest.shape)

(455, 30)
(114, 30)
(455, 1)
(114, 1)


In [ ]:
# y is in panda series (binary)
y.value_counts()
#not the total 80% of 569 we need 80% of both b and m values respectively so that the split what we do should be correct

0
0    357
1    212
Name: count, dtype: int64

In [ ]:
ytrain.value_counts()

0
0    290
1    165
Name: count, dtype: int64

In [ ]:
model = Sequential()


In [ ]:
model.add(Dense(16,input_dim=30,activation='relu'))
model.add(Dense(32,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model.fit(xtrain,ytrain,epochs=50,validation_data=(xtest,ytest))

Epoch 1/50


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


15/15 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.7623 - loss: 0.4990 - val_accuracy: 0.7719 - val_loss: 0.4539
Epoch 2/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8416 - loss: 0.3964 - val_accuracy: 0.8421 - val_loss: 0.3674
Epoch 3/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9224 - loss: 0.3051 - val_accuracy: 0.9211 - val_loss: 0.3045
Epoch 4/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9303 - loss: 0.2646 - val_accuracy: 0.9474 - val_loss: 0.2508
Epoch 5/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9714 - loss: 0.1973 - val_accuracy: 0.9561 - val_loss: 0.2041
Epoch 6/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9734 - loss: 0.1646 - val_accuracy: 0.9737 - val_loss: 0.1644
Epoch 7/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9573 - loss: 0.1627 - val_accuracy: 0.9737 - val_loss: 0.1340
Epoch 8/50
15/15 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9750 - loss: 0.1302 - val_accuracy: 0.9737 - val_loss: 0.1151
Ep

In [ ]:
ypred = model.predict(xtest)

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step


In [ ]:
ypred
ypred = ypred.round()


In [ ]:
ypred

array([[1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],

In [ ]:
ytest.values

array([[1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
    

In [ ]:
ypred.shape

(114, 1)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
ac = accuracy_score (ytest, ypred)
ac

0.9736842105263158

In [ ]:
cm=confusion_matrix(ytest,ypred)
cm

array([[67,  0],
       [ 3, 44]])